# Generated by Django 4.2.30 on 2026-06-26 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date et heure')),
                ('type_energie', models.CharField(choices=[('CARBURANT', 'Carburant'), ('RECHARGE', 'Recharge')], max_length=20, verbose_name="type d'énergie")),
                ('litres', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='litres (carburant)')),
                ('kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='kWh (recharge)')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='prix total')),
                ('kilometrage', models.PositiveIntegerField(verbose_name='kilométrage au relevé')),
                ('nom_station', models.CharField(blank=True, max_length=150, verbose_name='nom de la station')),
                ('localisation_station', models.CharField(blank=True, max_length=250, verbose_name='localisation de la station')),
                ('recu', models.FileField(blank=True, null=True, upload_to='recus_energie/%Y/%m/', verbose_name='reçu / facture')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to=settings.AUTH_USER_MODEL, verbose_name='chauffeur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='vehicules.vehicule', verbose_name='véhicule')),
            ],
            options={
                'verbose_name': 'consommation',
                'verbose_name_plural': 'consommations',
                'db_table': 'energie_consommations',
                'indexes': [models.Index(fields=['vehicule', 'date'], name='energie_con_vehicul_011f86_idx')],
            },
        ),
    ]
