# Generated by Django 4.2.30 on 2026-06-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True, verbose_name='immatriculation')),
                ('marque', models.CharField(max_length=100, verbose_name='marque')),
                ('modele', models.CharField(max_length=100, verbose_name='modèle')),
                ('annee', models.IntegerField(verbose_name='année')),
                ('type_vehicule', models.CharField(choices=[('VOITURE', 'Voiture'), ('MOTO', 'Moto'), ('CAMIONNETTE', 'Camionnette'), ('UTILITAIRE', 'Utilitaire'), ('CAMION', 'Camion')], max_length=20, verbose_name='type de véhicule')),
                ('motorisation', models.CharField(choices=[('ESSENCE', 'Essence'), ('DIESEL', 'Diesel'), ('ELECTRIQUE', 'Électrique'), ('HYBRIDE', 'Hybride'), ('HYBRIDE_RECHARGEABLE', 'Hybride Rechargeable')], max_length=30, verbose_name='motorisation')),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_UTILISATION', 'En utilisation'), ('EN_MAINTENANCE', 'En maintenance'), ('EN_CHARGE', 'En charge'), ('HORS_SERVICE', 'Hors service')], default='DISPONIBLE', max_length=20, verbose_name='statut')),
                ('kilometrage', models.PositiveIntegerField(default=0, verbose_name='kilométrage')),
                ('capacite_batterie', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='capacité batterie (kWh)')),
                ('autonomie', models.PositiveIntegerField(blank=True, null=True, verbose_name='autonomie (km)')),
                ('date_achat', models.DateField(verbose_name="date d'achat")),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="prix d'achat")),
                ('vin', models.CharField(max_length=50, unique=True, verbose_name='numéro de châssis (VIN)')),
                ('expiration_assurance', models.DateField(verbose_name='expiration assurance')),
                ('expiration_controle_technique', models.DateField(verbose_name='expiration contrôle technique')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'verbose_name': 'véhicule',
                'verbose_name_plural': 'véhicules',
                'db_table': 'vehicules',
                'indexes': [models.Index(fields=['immatriculation'], name='vehicules_immatri_f2ed2f_idx'), models.Index(fields=['statut'], name='vehicules_statut_3a3e6f_idx')],
            },
        ),
    ]
