# Generated by Django 4.2.30 on 2026-06-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='cgu_acceptees',
            field=models.BooleanField(default=False, verbose_name='CGU acceptées'),
        ),
    ]
