# Generated by Django 4.2.30 on 2026-06-26 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('type_affectation', models.CharField(choices=[('TEMPORAIRE', 'Temporaire'), ('PERMANENTE', 'Permanente')], default='TEMPORAIRE', max_length=20, verbose_name="type d'affectation")),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_chauffeur', to=settings.AUTH_USER_MODEL, verbose_name='chauffeur')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_creees', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='vehicules.vehicule', verbose_name='véhicule')),
            ],
            options={
                'verbose_name': 'affectation',
                'verbose_name_plural': 'affectations',
                'db_table': 'affectations',
                'indexes': [models.Index(fields=['vehicule', 'chauffeur'], name='affectation_vehicul_8673f5_idx')],
            },
        ),
    ]
