# Generated by Django 4.2.30 on 2026-06-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='kilometrage_depart',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='kilométrage au départ'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='kilometrage_retour',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='kilométrage au retour'),
        ),
    ]
