# Generated by Django 4.2.30 on 2026-06-26 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteEntretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('KILOMETRAGE', 'Kilométrage'), ('DATE', 'Date')], max_length=20, verbose_name="type d'alerte")),
                ('seuil_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='seuil (kilomètres)')),
                ('seuil_date', models.DateField(blank=True, null=True, verbose_name='seuil (date)')),
                ('actif', models.BooleanField(default=True, verbose_name='alerte active')),
                ('dernier_declenchement', models.DateTimeField(blank=True, null=True, verbose_name='dernier déclenchement')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='vehicules.vehicule', verbose_name='véhicule')),
            ],
            options={
                'verbose_name': "alerte d'entretien",
                'verbose_name_plural': "alertes d'entretien",
                'db_table': 'alertes_entretien',
            },
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_intervention', models.CharField(choices=[('REVISION', 'Révision'), ('VIDANGE', 'Vidange'), ('PNEUS', 'Changement de pneus'), ('CONTROLE_TECHNIQUE', 'Contrôle technique'), ('BATTERIE', 'Batterie'), ('AUTRE', 'Autre')], max_length=50, verbose_name="type d'intervention")),
                ('date_prevue', models.DateField(verbose_name='date prévue')),
                ('date_realisation', models.DateField(blank=True, null=True, verbose_name='date de réalisation')),
                ('kilometrage', models.PositiveIntegerField(verbose_name="kilométrage lors de l'entretien")),
                ('cout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='coût')),
                ('description', models.TextField(blank=True, verbose_name='description détaillée')),
                ('nom_garage', models.CharField(blank=True, max_length=150, verbose_name='nom du garage')),
                ('contact_garage', models.CharField(blank=True, max_length=150, verbose_name='contact du garage')),
                ('facture', models.FileField(blank=True, null=True, upload_to='factures_entretien/%Y/%m/', verbose_name='facture')),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='PLANIFIE', max_length=20, verbose_name='statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretiens_crees', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='vehicules.vehicule', verbose_name='véhicule')),
            ],
            options={
                'verbose_name': 'entretien',
                'verbose_name_plural': 'entretiens',
                'db_table': 'entretiens',
                'indexes': [models.Index(fields=['vehicule', 'date_prevue'], name='entretiens_vehicul_f175be_idx'), models.Index(fields=['statut'], name='entretiens_statut_dee60d_idx')],
            },
        ),
    ]
