# Generated by Django 4.2.30 on 2026-06-26 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entretiens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='chauffeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_entretiens', to=settings.AUTH_USER_MODEL, verbose_name='demandeur (chauffeur)'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='est_immediat',
            field=models.BooleanField(default=False, verbose_name='demande immédiate (panne)'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé')], default='PLANIFIE', max_length=30, verbose_name='statut'),
        ),
    ]
