# Generated by Django 4.2.30 on 2026-06-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretiens', '0002_entretien_chauffeur_entretien_est_immediat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='type_intervention',
            field=models.CharField(choices=[('REVISION', 'Révision'), ('VIDANGE', 'Vidange'), ('PNEUS', 'Changement de pneus'), ('CONTROLE_TECHNIQUE', 'Contrôle technique'), ('BATTERIE', 'Batterie 12V'), ('SYSTEME_HT', 'Système Haute Tension (VE)'), ('MOTEUR_ELEC', 'Moteur Électrique (VE)'), ('AUTRE', 'Autre')], max_length=50, verbose_name="type d'intervention"),
        ),
    ]
